/**
 * Copyright 2015-2021 Valery Silaev (http://vsilaev.com)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package net.tascalate.concurrent;

import java.time.Duration;
import java.util.NoSuchElementException;
import java.util.Optional;
import java.util.concurrent.CancellationException;
import java.util.concurrent.CompletionException;
import java.util.concurrent.TimeoutException;
import java.util.function.Consumer;
import java.util.function.Function;
import java.util.function.Predicate;
import java.util.function.Supplier;

/**
 * A monad representing a computation that may either result in a value ({@link Success})
 * or an exception ({@link Failure}).
 * <p>
 * Inspired by Scala's {@code Try} and Vavr's {@code Try}, this class provides a functional
 * way to handle exceptions without using traditional try-catch blocks. It safely captures
 * exceptions thrown inside mapping and filtering operations, wrapping them in a {@code Failure}.
 *
 * @param <R> the type of the value returned by the computation
 */
public abstract class Try<R> {

    /**
     * Returns {@code true} if this is a {@link Success}, {@code false} otherwise.
     *
     * @return whether this Try is a Success
     */
    public abstract boolean isSuccess();

    /**
     * Returns {@code true} if this is a {@link Failure}, {@code false} otherwise.
     *
     * @return whether this Try is a Failure
     */
    public abstract boolean isFailure();

    /** 
     * Extracts the value if successful, or throws an {@link IllegalStateException}.
     * <p>
     * Note: Unlike the package-private {@link #done()}, this method does not rethrow 
     * the underlying failure exception.
     * 
     * @return the value if this is a Success
     * @throws IllegalStateException if this is a Failure
     */
    public final R get() {
        if (isSuccess()) {
            return done();
        } else {
            throw new IllegalStateException("No result available for the failure");
        }
    }

    /**
     * Returns the underlying exception if this is a {@link Failure}.
     *
     * @return the cause of the failure
     * @throws UnsupportedOperationException if this is a {@link Success}
     */
    public abstract Throwable getCause();

    /**
     * Returns the contained value if successful, otherwise returns the provided default value.
     *
     * @param value the default value to return if this is a Failure
     * @return the success value or the default value
     */
    public final R orElse(R value) {
        return isSuccess() ? done() : value;
    }

    /**
     * Returns the contained value if successful, otherwise evaluates and returns the fallback value.
     *
     * @param fallback the supplier to evaluate if this is a Failure
     * @return the success value or the evaluated fallback value
     */
    public final R orElseGet(Supplier<? extends R> fallback) {
        return isSuccess() ? done() : fallback.get();
    }

    /**
     * Returns the contained value if successful, otherwise throws an exception generated by the provider.
     *
     * @param exceptionProvider the function to map the failure cause to an exception to throw
     * @param <X> the type of the exception to throw
     * @return the success value
     * @throws X if this is a Failure
     */
    public final <X extends Throwable> R orElseThrow(Function<? super Throwable, ? extends X> exceptionProvider) throws X {
        if (isSuccess()) {
            return done();
        } else {
            throw exceptionProvider.apply(getCause());
        }
    }

    /**
     * Transforms the value if this is a {@link Success}.
     * If the mapper function throws an exception, the result is a {@link Failure} containing that exception.
     * If this is already a {@link Failure}, it is returned unchanged.
     *
     * @param mapper the function to apply to the success value
     * @param <U> the type of the new value
     * @return a new Try containing the mapped value, or the original Failure
     */
    public final <U> Try<U> map(Function<? super R, ? extends U> mapper) {
        if (isSuccess()) {
            try {
                return success(mapper.apply(done()));
            } catch (Throwable t) {
                return failure(t);
            }
        }
        @SuppressWarnings("unchecked")
        Try<U> self = (Try<U>) this;
        return self;
    }

    /**
     * Transforms the value into another {@link Try} if this is a {@link Success}.
     * If the mapper function throws an exception, the result is a {@link Failure} containing that exception.
     * If this is already a {@link Failure}, it is returned unchanged.
     *
     * @param mapper the function to apply to the success value, returning a new Try
     * @param <U> the type of the new value
     * @return the Try returned by the mapper, or the original Failure
     */
    public final <U> Try<U> flatMap(Function<? super R, ? extends Try<U>> mapper) {
        if (isSuccess()) {
            try {
                return mapper.apply(done());
            } catch (Throwable t) {
                return failure(t);
            }
        }
        @SuppressWarnings("unchecked")
        Try<U> self = (Try<U>) this;
        return self;
    }

    // ==========================================
    // Filtering
    // ==========================================

    /**
     * Filters a successful value; converts to a {@link Failure} if the predicate yields false.
     * If the predicate fails, the resulting Try will be a Failure with a {@link NoSuchElementException}.
     *
     * @param predicate the predicate to apply to a successful value
     * @return this Try if it is a Failure or the predicate holds, otherwise a Failure
     */
    public final Try<R> filter(Predicate<? super R> predicate) {
        return filter(predicate, value -> new NoSuchElementException("Predicate does not hold for " + value));
    }

    /**
     * Filters a successful value with a custom exception factory when the predicate fails.
     *
     * @param predicate    the predicate to apply to a successful value
     * @param errorFactory the factory to create an exception if the predicate returns false
     * @return this Try if it is a Failure or the predicate holds, otherwise a Failure containing the generated exception
     */
    public final Try<R> filter(Predicate<? super R> predicate, Function<? super R, ? extends Throwable> errorFactory) {
        if (isSuccess()) {
            try {
                R val = done();
                if (predicate.test(val)) {
                    return this;
                } else {
                    return failure(errorFactory.apply(val));
                }
            } catch (Throwable t) {
                return failure(t);
            }
        }
        return this;
    }

    // ==========================================
    // Recovery & Fallbacks
    // ==========================================

    /**
     * Recovers from a failure by transforming the underlying exception into a new successful value.
     * If the recovery function throws, the result is a {@link Failure} containing the new exception.
     *
     * @param recovery the function to map the exception to a recovery value
     * @return a Success containing the recovered value if this was a Failure, otherwise this Try
     */
    public final Try<R> recover(Function<? super Throwable, ? extends R> recovery) {
        if (isFailure()) {
            try {
                return success(recovery.apply(getCause()));
            } catch (Throwable t) {
                return failure(t);
            }
        }
        return this;
    }

    /**
     * Recovers from a failure by mapping the exception to an alternative {@link Try} monad.
     * If the recovery function throws, the result is a {@link Failure} containing the new exception.
     *
     * @param recovery the function to map the exception to an alternative Try
     * @return the alternative Try if this was a Failure, otherwise this Try
     */
    @SuppressWarnings("unchecked")
    public final Try<R> recoverWith(Function<? super Throwable, ? extends Try<? extends R>> recovery) {
        if (isFailure()) {
            try {
                return (Try<R>) recovery.apply(getCause());
            } catch (Throwable t) {
                return failure(t);
            }
        }
        return this;
    }

    // ==========================================
    // Side-Effect Consumers (Callbacks)
    // ==========================================

    /**
     * Invokes the consumer if this is a {@link Success}.
     *
     * @param action the action to perform on the success value
     * @return this Try for method chaining
     */
    public final Try<R> onSuccess(Consumer<? super R> action) {
        if (isSuccess()) {
            action.accept(done());
        }
        return this;
    }

    /**
     * Invokes the consumer if this is a {@link Failure}.
     *
     * @param action the action to perform on the failure cause
     * @return this Try for method chaining
     */
    public final Try<R> onFailure(Consumer<? super Throwable> action) {
        if (isFailure()) {
            action.accept(getCause());
        }
        return this;
    }

    // ==========================================
    // Interoperability Conversions
    // ==========================================

    /**
     * Converts this Try into an {@link Optional}.
     * A {@link Success} becomes an Optional containing the value (or empty if the value is null).
     * A {@link Failure} becomes {@link Optional#empty()}.
     *
     * @return an Optional representing the success value
     */
    public final Optional<R> toOptional() {
        return isSuccess() ? Optional.ofNullable(done()) : Optional.empty();
    }

    // ==========================================
    // Factories
    // ==========================================

    /**
     * Creates a successful {@link Try} containing the given value.
     *
     * @param result the success value
     * @param <R> the type of the value
     * @return a Success containing the value
     */
    public static <R> Try<R> success(R result) {
        return new Success<>(result);
    }

    /**
     * Creates a failed {@link Try} containing the given exception.
     *
     * @param error the failure cause
     * @param <R> the type of the value (had it succeeded)
     * @return a Failure containing the exception
     */
    public static <R> Try<R> failure(Throwable error) {
        return new Failure<>(error);
    }

    // ==========================================
    // Subclasses
    // ==========================================

    /**
     * Represents a successful computation.
     *
     * @param <R> the type of the value
     */
    public static final class Success<R> extends Try<R> {
        private final R result;

        // Package-private constructor to enforce factory usage
        Success(R result) {
            this.result = result;
        }

        @Override public R done() { 
            return result; 
        }
        
        @Override public boolean isSuccess() { 
            return true; 
        }
        
        @Override public boolean isFailure() { 
            return false; 
        }
        
        @Override public Throwable getCause() { 
            throw new UnsupportedOperationException("Success has no cause"); 
        }
        
        @Override Promise<R> asPromise() { 
            return Promises.success(result); 
        }
        
        @Override boolean isCancel() { 
            return false; 
        }
    }

    /**
     * Represents a failed computation.
     *
     * @param <R> the type of the value (had it succeeded)
     */
    public static final class Failure<R> extends Try<R> {
        private final Throwable error;

        // Package-private constructor
        Failure(Throwable error) {
            this.error = error;
        }

        @Override public R done() {
            if (error instanceof Error) {
                throw (Error) error;
            } else if (error instanceof CancellationException) {
                throw (CancellationException) error;
            } else {
                throw SharedFunctions.wrapCompletionException(error); 
            }
        }
        
        @Override public boolean isSuccess() { 
            return false; 
        }
        
        @Override public boolean isFailure() { 
            return true; 
        }
        
        @Override public Throwable getCause() { 
            return error; 
        }
        
        @Override Promise<R> asPromise() { 
            return Promises.failure(error); 
        }
        
        @Override boolean isCancel() {
            Throwable ex = SharedFunctions.unwrapCompletionException(error);
            return ex instanceof CancellationException;
        }
    }

    // ==========================================
    // Package-Private Internal Helpers
    // ==========================================

    /**
     * Extracts the value if successful, or throws the underlying exception.
     * Used internally by the Tascalate framework to bridge with Promises.
     *
     * @return the success value
     * @throws RuntimeException {@link CancellationException} or {@link CompletionException} the failure cause if this is a Failure
     */
    abstract R done();

    /**
     * Checks if the underlying failure is a cancellation.
     *
     * @return true if this is a Failure caused by a CancellationException
     */
    abstract boolean isCancel();

    /**
     * Converts this Try into a Tascalate {@link Promise}.
     *
     * @return a successfully or exceptionally completed Promise
     */
    abstract Promise<R> asPromise();

    /**
     * Internal helper to handle a result/error pair from a CompletionStage,
     * optionally cancelling a timeout Promise.
     *
     * @param result the success value (may be null)
     * @param error the failure cause (may be null)
     * @param timeout an optional timeout Promise to cancel
     * @param <R> the type of the value
     * @return a Success or Failure based on the provided error
     */
    static <R> Try<R> handle(R result, Throwable error, Promise<?> timeout) {
        if (null != timeout) {
            timeout.cancel(true);
        }
        return null == error ? Try.success(result) : Try.failure(error);
    }
    
    /**
     * Internal helper to convert a null result into a TimeoutException Failure.
     *
     * @param result the Try result (may be null if timed out)
     * @param duration the timeout duration for the exception message
     * @param <T> the type of the value
     * @return the original result, or a Failure with TimeoutException if result is null
     */
    static <T> Try<T> doneOrTimeout(Try<T> result, Duration duration) {
        return null != result ? result : Try.failure(new TimeoutException("Timeout after " + duration));
    }
    
    /**
     * Wraps a Supplier into a Supplier of Try, catching any thrown exceptions.
     *
     * @param supplier the supplier to wrap
     * @param <R> the type of the value
     * @return a Supplier that returns a Success or Failure
     */
    static <R> Supplier<Try<R>> call(Supplier<? extends R> supplier) {
        return () -> {
            try {
                return Try.success(supplier.get());
            } catch (Throwable ex) {
                return Try.failure(ex);
            }
        };
    }

    /**
     * Returns a cached, singleton Success containing null.
     *
     * @param <R> the type of the value
     * @return a Success containing null
     */
    @SuppressWarnings("unchecked")
    static <R> Try<R> nothing() {
        return (Try<R>) NOTHING;
    }
    
    private static final Try<Object> NOTHING = success(null); 
}